### ISSUE TITLE
RHINO 설치 문제

### ISSUE THREAD

**Issue by ehsong** [SukjaeChoi/RHINO#12]
안녕하세요, 블로그에 설명대로 설치를 했는데 결과값이 NULL이 나옵니다:

> getMorph("우리의 소원은 통일입니다.")     
Constructing Dictionaries...
Wait seconds...
Current path: Library/Frameworks/R.framework/Versions/3.6/Resources/library/RHINO/java/resource/
NULL

일단 설치는 직접 압축 파일 풀어서 R library들 있는 폴더에 풀었고 resource 폴더에 파일들이 다 있는 것도 확인했는데 왜 NULL 값이 나올까요?

**Comment by SukjaeChoi** [comment]
답변이 늦어 미안합니다. 별도의 알림을 받지 않고, 가끔 업데이트가 있을 때만 들어옵니다.
직접 압축 파일을 풀었음에도 불구하고 설치가 되지 않는다면 참 답변하기 어려운 부분입니다.
다만, 이번에 Linux 버전에 더 친화적인 버전을 블로그와 이곳에 업데이트를 했으니 다시 한 번 확인해 보시면 좋겠습니다. 
단, 맥에서는 아직 되지 않습니다.

**Comment by seonghobae** [comment]
자바 프로그램 내부 파라미터가 윈도우즈 기준으로 설정돼 있습니다. 교수님께서 Pull Request 등을 잦아주시지 않고, 자바 원본을 공개하지는 않으셔서 보완책을 기여할 수가 없었습니다.

**Comment by SukjaeChoi** [comment]
> 자바 프로그램 내부 파라미터가 윈도우즈 기준으로 설정돼 있습니다. 교수님께서 Pull Request 등을 잦아주시지 않고, 자바 원본을 공개하지는 않으셔서 보완책을 기여할 수가 없었습니다.

위에서 올린 바와 같이 2.7.0에서는 linux에서 잘 돌아가도록 했습니다.
개인 컴퓨터의 우분투와 코랩에서는 잘 됩니다.
그러나 맥에서는 아직 잘 되지 않습니다.

배성호님께서 기여를 해주신 부분은 감사하나,
개발 과정을 같이 공유하여 진행할 계획은 없습니다.
MIT 라이센스를 준수하시면 파생형을 만드시는 것은 가능합니다.

RHINO 2.6.2 까지는 아래에서 소스코드를 공개했습니다.
https://sourceforge.net/projects/koreananalyzer/
