### ISSUE TITLE
R package 판올림

### ISSUE THREAD

**Issue by bgnkim** [SukjaeChoi/RHINO#13]
안녕하세요,
https://github.com/koalanlp/koalanlp/issues/29 에서 논의하셨던 것처럼, R package의 판올림을 진행하실 수 있게
여기 issue를 하나 올려드렸습니다.

> 1. Java 버전이나 R 버전을 최신버전으로 올려주실 수 있을까요?
> R은 해당 프로젝트에 이슈 남겨놓겠습니다.
> Java Jar 파일이 변경되면 해당 파일을 주셔도 좋습니다.
>
> 2. Java Jar 파일의 변경사항을 쉽게 반영할 수 있도록, Maven 계열 저장소에 올려주실 수도 있으실지요?
>     - OSS sonatype, Maven central, JFrog, Jitpack, Github packages 무엇이든 괜찮습니다.
>     - 올리신 후에 (Shell이 아닌) Java에서 형태소분석을 하는 간단한 사용법도 알려주시면 그대로 KoalaNLP에 반영하겠습니다.

작업을 다 마치신 후에 여기에 알려주셔도 확인하고 KoalaNLP에 반영하도록 하겠습니다.
빠르게 피드백 반영해주신다니, 감사드립니다.

**Comment by SukjaeChoi** [comment]
안녕하세요,

RHINO의 최신버전 3.8.0 (LTS)을 올렸습니다.
1) 특수문자가 모두 나오도록 처리
2) Java Client 프로그램의 접속 문제 수정
3) GitHub 버전 중 resource 폴더의 파일 정리
4) 사전 소량 추가 등이 개선 사항이었습니다.

그리고 Maven에도 올리려고 여러 시간 시도하여 절반 이상 진행하였다가
Maven의 컴파일 및 라이브러리를 사용하는 패턴이 이전과 다른 것을 알고 중간에 포기했습니다.
특히 이번 3.8.0 을 마지막으로 매우 오랫동안은 공개버전을 내지 않을 것이기에 Maven 등재 필요성을 못느끼게 되었습니다.
나중에 공개버전을 더 내놓게 되면 그 때는 알려드리고 꼭 Maven 등재를 하도록 하겠습니다.

jar을 직접 드리려고 했는데, 연락처를 알지 못하여 아래에 경로만 남깁니다.
아래의 경로에 있는 rhino.jar 파일과 resource 폴더의 6개 텍스트 파일만 있으면 됩니다.
RHINO/inst/java/


감사합니다.

**Comment by bgnkim** [comment]
안녕하세요.
올려주신 3.8.0으로 확인해보았습니다.
알려주신대로 모든 resource를 정상적으로 위치시키고 Java 및 Python 3.5에서 테스트했으나 특수문자는 처리되었지만 특수문자 주변 문자열에 문제가 있습니다.

다음 문장으로 테스트했습니다.
```text
【그】가 졸음이다. 사랑스러웠기에.
```

다음과 같은 결과가 도출됩니다.
```text
【그】가	【그】/NA + /NA
졸음이다	졸음/NNG + 이/VCP + 다/EF
.	./SF
사랑스러웠기에	사랑/XR + 스러웠/NA + 기/ETN + 에/JKB
.	./SF
```

보시면 첫번째 단어에서 조사 `가`가 사라지는 것을 확인하실 수 있습니다.

실행 코드는 다음과 같습니다.
자바의 경우: resource 폴더에 6개 텍스트 파일을 삽입한 상태에서
```sh
java -cp rhino.jar rhino.MainClass
```

Python의 경우: (버전 3.5)
```python3
>>> import rhinoMorph
>>> rn = rhinoMorph.startRhino()
filepath:  /home/bydelta/git/sample/virtenv/lib/python3.5/site-packages
classpath:  /home/bydelta/git/sample/virtenv/lib/python3.5/site-packages/rhinoMorph/lib/rhino.jar
Constructing Dictionaries...
Current mode: python	Current path: /home/bydelta/git/sample/virtenv/lib/python3.5/site-packages/rhinoMorph/resource/
Constructing Dictionaries Completed.

RHINO started!
>>> text='【그】가 졸음이다. 사랑스러웠기에.'
>>> print(rhinoMorph.wholeResult_text(rn, text))
【그】가	【그】/NA + /NA
졸음이다	졸음/NNG + 이/VCP + 다/EF
.	./SF
사랑스러웠기에	사랑/XR + 스러웠/NA + 기/ETN + 에/JKB
.	./SF
```

우선은 3.7.8 버전으로 유지하고 업데이트 해주시는 것을 기다리도록 하겠습니다.

감사합니다.

**Comment by SukjaeChoi** [comment]
알려주셔서 감사드립니다. 다음 버전에서는 관련 문제들이 더 있는지 보도록 하겠습니다.
